/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: rbreve (https://sketchfab.com/rbreve)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/voxel-twitter-bird-8da01234347a4193b06f0b2f07113d40
title: Voxel Twitter Bird
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Bird(props) {
  const { nodes, materials } = useGLTF("/voxel_twitter_bird.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[6, -12, -15]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_3.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[9, -12, -15]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_5.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[3, -12, -15]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_7.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[9, -12, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_9.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[3, -12, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_11.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[6, -12, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_13.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[3, -21, -12]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_15.geometry}
              material={materials.material_5}
            />
          </group>
          <group position={[3, -21, -3]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_17.geometry}
              material={materials.material_5}
            />
          </group>
          <group position={[6, -18, -3]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_19.geometry}
              material={materials.material_5}
            />
          </group>
          <group position={[6, -18, -12]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_21.geometry}
              material={materials.material_5}
            />
          </group>
          <group position={[0, -12, -3]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_23.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[0, -12, -6]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_25.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[0, -12, -9]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_27.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[0, -12, -12]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_29.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[0, -9, -12]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_31.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[0, -9, -9]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_33.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[0, -9, -6]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_35.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[0, -9, -3]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_37.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[9, -3, -9]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_39.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[9, -3, -12]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_41.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[9, -3, -6]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_43.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[9, -3, -3]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_45.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[9, 0, -3]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_47.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[9, 0, -12]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_49.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[9, 0, -9]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_51.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[9, 0, -6]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_53.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[9, 3, -3]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_55.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[9, 3, -6]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_57.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[9, 3, -9]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_59.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[9, 3, -12]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_61.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[9, 6, -9]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_63.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[9, 6, -3]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_65.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[9, 6, -6]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_67.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[9, 6, -12]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_69.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[9, 9, -3]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_71.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[9, 9, -6]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_73.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[9, 9, -9]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_75.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[9, 9, -12]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_77.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[3, -15, -9]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_79.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[3, -15, -12]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_81.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[3, -15, -6]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_83.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[3, -15, -3]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_85.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[6, -15, -3]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_87.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[6, -15, -12]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_89.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[3, -12, -12]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_91.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[3, -12, -3]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_93.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[6, -21, -12]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_95.geometry}
              material={materials.material_5}
            />
          </group>
          <group position={[6, -21, -3]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_97.geometry}
              material={materials.material_5}
            />
          </group>
          <group position={[18, -9, -9]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_99.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[18, -9, -6]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_101.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[15, -12, -6]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_103.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[15, -12, -9]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_105.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[6, -6, -6]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_107.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[6, -6, -9]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_109.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[12, -15, -6]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_111.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[12, -15, -9]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_113.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[12, -12, -6]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_115.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[12, -12, -12]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_117.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[12, -12, -3]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_119.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[12, -12, -9]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_121.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[15, -9, -9]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_123.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[12, -9, -3]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_125.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[15, -9, -6]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_127.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[12, -9, -6]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_129.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[12, -9, -12]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_131.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[9, -15, -6]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_133.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[9, -15, -9]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_135.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[6, -15, -9]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_137.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[6, -15, -6]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_139.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[9, -15, -3]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_141.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[9, -15, -12]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_143.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[9, -12, -12]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_145.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[9, -12, -9]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_147.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[9, -12, -6]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_149.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[9, -12, -3]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_151.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[9, -9, -3]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_153.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[9, -9, -9]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_155.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[9, -9, -6]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_157.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[9, -9, -12]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_159.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[6, -12, -6]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_161.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[6, -12, -9]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_163.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[6, -12, -12]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_165.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[6, -12, -3]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_167.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[3, -12, -6]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_169.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[3, -12, -9]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_171.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[3, -9, -3]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_173.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[6, -9, -3]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_175.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[6, -9, -12]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_177.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[3, -9, -12]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_179.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[6, -9, -6]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_181.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[6, -9, -9]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_183.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[3, -9, -6]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_185.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[3, -9, -9]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_187.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[3, -6, -9]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_189.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[3, -6, -6]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_191.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[0, 12, -9]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_193.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[3, 12, -9]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_195.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[0, 12, -6]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_197.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[3, 12, -6]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_199.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[-3, 0, -9]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_201.geometry}
              material={materials.material_4}
            />
          </group>
          <group position={[-3, 0, -6]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_203.geometry}
              material={materials.material_4}
            />
          </group>
          <group position={[6, -3, -12]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_205.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[6, 0, -12]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_207.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[6, 3, -12]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_209.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[6, 6, -12]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_211.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[6, 9, -12]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_213.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[6, -3, -9]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_215.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[6, 0, -9]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_217.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[6, 3, -9]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_219.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[6, 6, -9]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_221.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[6, 9, -9]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_223.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[6, -3, -6]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_225.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[6, 0, -6]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_227.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[6, 3, -6]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_229.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[6, 6, -6]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_231.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[6, 9, -6]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_233.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[6, -3, -3]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_235.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[6, 0, -3]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_237.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[6, 3, -3]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_239.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[6, 6, -3]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_241.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[6, 9, -3]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_243.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[6, -3, -15]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_245.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[6, 3, -15]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_247.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[6, 0, -15]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_249.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[6, 6, -15]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_251.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[6, 9, -15]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_253.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[12, -9, -9]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_255.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[6, -3, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_257.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[6, 0, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_259.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[6, 6, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_261.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[6, 3, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_263.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[6, 9, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_265.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[3, -3, -15]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_267.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[3, -3, -9]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_269.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[3, -3, -12]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_271.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[3, -3, -6]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_273.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[3, -3, -3]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_275.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[3, -3, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_277.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[0, -3, -15]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_279.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[0, -3, -12]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_281.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[0, -3, -9]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_283.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[0, -3, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_285.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[0, -3, -6]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_287.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[0, -3, -3]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_289.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[3, 3, -15]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_291.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[3, 0, -15]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_293.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[3, 0, -12]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_295.geometry}
              material={materials.material_3}
            />
          </group>
          <group position={[3, 3, -12]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_297.geometry}
              material={materials.material_3}
            />
          </group>
          <group position={[3, 3, -9]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_299.geometry}
              material={materials.material_3}
            />
          </group>
          <group position={[3, 0, -9]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_301.geometry}
              material={materials.material_3}
            />
          </group>
          <group position={[3, 0, -6]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_303.geometry}
              material={materials.material_3}
            />
          </group>
          <group position={[3, 3, -6]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_305.geometry}
              material={materials.material_3}
            />
          </group>
          <group position={[3, 3, -3]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_307.geometry}
              material={materials.material_3}
            />
          </group>
          <group position={[3, 0, -3]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_309.geometry}
              material={materials.material_3}
            />
          </group>
          <group position={[3, 0, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_311.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[3, 3, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_313.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[3, 6, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_315.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[3, 6, -6]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_317.geometry}
              material={materials.material_3}
            />
          </group>
          <group position={[3, 6, -3]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_319.geometry}
              material={materials.material_3}
            />
          </group>
          <group position={[3, 6, -9]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_321.geometry}
              material={materials.material_3}
            />
          </group>
          <group position={[3, 6, -12]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_323.geometry}
              material={materials.material_3}
            />
          </group>
          <group position={[3, 6, -15]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_325.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[3, 9, -15]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_327.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[3, 9, -12]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_329.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[3, 9, -9]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_331.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[3, 9, -6]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_333.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[3, 9, -3]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_335.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[3, 9, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_337.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[0, 0, -15]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_339.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[0, 3, -15]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_341.geometry}
              material={materials.material_1}
            />
          </group>
          <group position={[0, 6, -15]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_343.geometry}
              material={materials.material_1}
            />
          </group>
          <group position={[0, 9, -15]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_345.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[0, 0, -12]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_347.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[0, 0, -9]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_349.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[0, 3, -12]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_351.geometry}
              material={materials.material_2}
            />
          </group>
          <group position={[0, 3, -9]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_353.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[0, 0, -6]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_355.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[0, 3, -6]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_357.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[0, 3, -3]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_359.geometry}
              material={materials.material_2}
            />
          </group>
          <group position={[0, 0, -3]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_361.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[0, 6, -12]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_363.geometry}
              material={materials.material_1}
            />
          </group>
          <group position={[0, 6, -9]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_365.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[0, 6, -6]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_367.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[0, 6, -3]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_369.geometry}
              material={materials.material_1}
            />
          </group>
          <group position={[0, 9, -12]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_371.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[0, 9, -9]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_373.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[0, 9, -6]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_375.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[0, 9, -3]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_377.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[0, 9, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_379.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[0, 6, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_381.geometry}
              material={materials.material_1}
            />
          </group>
          <group position={[0, 3, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_383.geometry}
              material={materials.material_1}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_384.geometry}
            material={materials.material_0}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/voxel_twitter_bird.glb");
