/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: rossiotti (https://sketchfab.com/rossiotti)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/lion-voxel-a30c874a645749108423449283c0ff2c
title: Lion Voxel
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Lion(props) {
  const { nodes, materials } = useGLTF("/lion_voxel.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={materials["Scene_-_Root"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/lion_voxel.glb");
