/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Dickyhewage (https://sketchfab.com/Dickyhewage)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/x-4-stormwing-fortnite-baeccfb0e7d74620a578b027f9db9445
title: X-4 Stormwing | Fortnite
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Plane(props) {
  const { nodes, materials } = useGLTF("/x-4_stormwing__fortnite.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[0, 0, 0]}>
        <group rotation={[0, 0, 0]}>
          <group position={[0, 0.46, 0.07]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pCube165_pasted__Texture_0.geometry}
              material={materials.pasted__Texture}
            />
          </group>
          <group position={[0, 0.48, -4.22]} scale={[0.69, 0.94, 0.14]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pCube166_pasted__Texture_0.geometry}
              material={materials.pasted__Texture}
            />
          </group>
          <group position={[0, 0.63, -4.29]} scale={[0.34, 0.4, 0.08]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pCube167_pasted__Texture_0.geometry}
              material={materials.pasted__Texture}
            />
          </group>
          <group
            position={[0, 0.74, -1.7]}
            rotation={[0.07, 0, 0]}
            scale={[0.86, 0.23, 1.09]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pCube168_pasted__Texture_0.geometry}
              material={materials.pasted__Texture}
            />
          </group>
          <group position={[0, 1.16, -0.57]} scale={[0.15, 1.25, 0.57]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pCube169_pasted__Texture_0.geometry}
              material={materials.pasted__Texture}
            />
          </group>
          <group position={[0, 0.79, -3.01]} scale={[6.83, 0.17, 1.54]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pCube170_pasted__Texture_0.geometry}
              material={materials.pasted__Texture}
            />
          </group>
          <group
            position={[0, 0.55, -1.57]}
            rotation={[0.07, 0, 0]}
            scale={[0.87, 0.24, 1.11]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pCube171_pasted__Texture_0.geometry}
              material={materials.pasted__Texture}
            />
          </group>
          <group position={[0, 0.08, -3.01]} scale={[6.83, 0.17, 1.54]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pCube172_pasted__Texture_0.geometry}
              material={materials.pasted__Texture}
            />
          </group>
          <group position={[0.92, 0.46, -3.29]} scale={[0.15, 0.62, 0.16]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pCube173_pasted__Texture_0.geometry}
              material={materials.pasted__Texture}
            />
          </group>
          <group position={[0.92, 0.46, -2.52]} scale={[0.15, 0.62, 0.16]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pCube174_pasted__Texture_0.geometry}
              material={materials.pasted__Texture}
            />
          </group>
          <group position={[-0.9, 0.46, -2.52]} scale={[0.15, 0.62, 0.16]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pCube175_pasted__Texture_0.geometry}
              material={materials.pasted__Texture}
            />
          </group>
          <group position={[-0.9, 0.46, -3.29]} scale={[0.15, 0.62, 0.16]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pCube176_pasted__Texture_0.geometry}
              material={materials.pasted__Texture}
            />
          </group>
          <group
            position={[0, 1, -3.07]}
            rotation={[0.07, 0, 0]}
            scale={[0.86, 0.23, 1.09]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pCube177_pasted__Texture_0.geometry}
              material={materials.pasted__Texture}
            />
          </group>
          <group position={[0, -0.3, -0.11]} rotation={[0.08, 0, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pCube182_pasted__Texture_0.geometry}
              material={materials.pasted__Texture}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube193_pasted__Texture_0.geometry}
            material={materials.pasted__Texture}
          />
          <group position={[0.94, 0, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pCube194_pasted__Texture_0.geometry}
              material={materials.pasted__Texture}
            />
          </group>
          <group
            position={[0.02, 0.66, -4.47]}
            rotation={[0, 0, -0.76]}
            scale={[0.21, 0.21, 0.52]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pCube196_pasted__Texture_0.geometry}
              material={materials.pasted__Texture}
            />
          </group>
          <group
            position={[0, 3.8, -3.99]}
            rotation={[-1.62, 0, 0]}
            scale={[1, 1, 0.69]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pCube199_pasted__Texture_0.geometry}
              material={materials.pasted__Texture}
            />
          </group>
          <group
            position={[2.69, -0.92, -3.74]}
            rotation={[1.52, 1.02, -Math.PI]}
            scale={[1, 1, 0.69]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pCube200_pasted__Texture_0.geometry}
              material={materials.pasted__Texture}
            />
          </group>
          <group
            position={[-2.76, -0.74, -3.75]}
            rotation={[1.52, -1.1, -Math.PI]}
            scale={[1, 1, 0.69]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pCube201_pasted__Texture_0.geometry}
              material={materials.pasted__Texture}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube205_pasted__Texture_0.geometry}
            material={materials.pasted__Texture}
          />
          <group position={[-1.75, 0, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pCube206_pasted__Texture_0.geometry}
              material={materials.pasted__Texture}
            />
          </group>
          <group position={[0.92, 0.86, -3.01]} scale={[0.44, 0.17, 1.63]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pCube207_pasted__Texture_0.geometry}
              material={materials.pasted__Texture}
            />
          </group>
          <group position={[-0.9, 0.86, -3.01]} scale={[0.44, 0.17, 1.63]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pCube208_pasted__Texture_0.geometry}
              material={materials.pasted__Texture}
            />
          </group>
          <group position={[0, 0.53, -0.37]} scale={[1.7, 0.09, 0.67]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pCube209_pasted__Texture_0.geometry}
              material={materials.pasted__Texture}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube214_pasted__Texture_0.geometry}
            material={materials.pasted__Texture}
          />
          <group position={[0.02, 0, 0]} scale={[-1, 1, 1]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pCube215_pasted__Texture_0.geometry}
              material={materials.pasted__Texture}
            />
          </group>
          <group position={[-0.44, 0.45, 3.7]} scale={1.09}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pCube216_pasted__Texture_0.geometry}
              material={materials.pasted__Texture}
            />
          </group>
          <group position={[0.51, 0.99, -2.14]} scale={[0.3, 0.34, 0.19]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pCube217_pasted__Texture_0.geometry}
              material={materials.pasted__Texture}
            />
          </group>
          <group position={[0.51, 0.99, -2.09]} scale={[0.21, 0.23, 0.13]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pCube218_pasted__Texture_0.geometry}
              material={materials.pasted__Texture}
            />
          </group>
          <group position={[0.51, 0.97, -2.07]} scale={[0.03, 0.16, 0.13]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pCube219_pasted__Texture_0.geometry}
              material={materials.pasted__Texture}
            />
          </group>
          <group position={[0.51, 0.25, -2.05]} scale={[0.16, 0.18, 0.05]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pCube220_pasted__Texture_0.geometry}
              material={materials.pasted__Texture}
            />
          </group>
          <group position={[-0.53, 0.25, -2.06]} scale={[0.16, 0.18, 0.05]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pCube221_pasted__Texture_0.geometry}
              material={materials.pasted__Texture}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube222_pasted__Texture_0.geometry}
            material={materials.pasted__Texture}
          />
          <group position={[-0.01, 1.2, -3.39]} scale={[0.13, 0.16, 0.06]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pCube223_pasted__Texture_0.geometry}
              material={materials.pasted__Texture}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/x-4_stormwing__fortnite.glb");
