/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: ParuthidotExE (https://sketchfab.com/ParuthidotExE)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/cubes-0065-3cd899d79e664636b14fc84781cd746d
title: Cubes 0065
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function PurpleCube(props) {
  const { nodes, materials } = useGLTF("/purple_cube.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.11}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group scale={[-1, 1, 1]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_4.geometry}
              material={materials["cubes_01-Material"]}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/cubes_0065.glb");
