/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Joanna (https://sketchfab.com/taratuta)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/pegasus-rainbow-voxel-art-3d6ad17050e7425e94a9441028552c1b
title: Pegasus Rainbow Voxel art
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Unicorn(props) {
  const { nodes, materials } = useGLTF("/pegasus_rainbow_voxel_art.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={materials.palette}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/pegasus_rainbow_voxel_art.glb");
